server:
  port: ${PORT:8081}

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate.ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/book_db?user=root&password=root
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root